name: Build more-modules app

on:
  workflow_dispatch: { }
  push: { }
  pull_request: { }

# Minimum permissions required by skip-duplicate-actions
permissions:
  actions: write
  contents: read

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: semeru

      - id: install-mvnd
        uses: ./.github/actions/install-mvnd

      - name: Build application with Maven
        shell: bash
        run: |
          cd demo-resources/app-more-modules || exit 1
          ${{ steps.install-mvnd.outputs.mvnd-dir }}/mvnd --batch-mode -errors --no-transfer-progress verify
